# 全局设置
Options:
  # 语言
  Language: "zh_CN"
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # OP 版本更新通知
  OP-Notify: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false

# Bot 设置
Bot:
  # HTTP 设置
  HTTP:
    URL: http://127.0.0.1:3000
  # WebHook 设置
  WebHook:
    Enable: true
    Port: 5700

# 数据库设置
Database:
  # 存储方式 (MYSQL, SQLITE)
  Type: SQLITE
  # MySQL 存储设置
  MySQL:
    host: localhost
    port: 3306
    user: root
    password: password
    database: minecraft
  # SQLite 存储设置
  SQLite:
    file: sqlite.db

# 数据缓存设置
Cache:
  # 缓存方式 (LOCAL)
  Type: LOCAL