# 全局设置
Options:
  # 语言
  Language: "zh_CN"
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # OP 版本更新通知
  OP-Notify: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false

# Bot 设置
Bot:
  # HTTP API 服务器地址
  API: "http://127.0.0.1:3000/"
  # HTTP 上报服务器端口
  Post: 8080